# Book settings
title: My_DS_jupyter_book
author: Lee Chaehyeon
logo: own_logo.png

# Execute settings
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ichaehyeon748/2026-Data-Structure-Course
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true